### ISSUE TITLE
What about waitOn while using PageObjects?

### ISSUE THREAD

**Issue by chadrickm** [jimholmes/UIAutomationWorkshop#1]
Hope you don't mind me asking a question in the Issues list but I'm guessing this will get to your email and give you a little context on what my question is about.

As I'm here at work getting ready to demo some stuff I learned from your workshop it occurs to me that I don't know how to do WaitOn while working with page objects. Any advise? Also would it be possible to add a readme with the resources you pointed us to? Specifically their were two bloggers that write a ton about UI testing.

Thanks Jim - The workshop was great!

**Comment by jimholmes** [comment]
Here is fine. Feel free to ask in mail, also: jim@GuidepostSystems.com

There are a couple ways to work with wait conditions when using PageObects. If you're using a property, say for working with the [dropdown demo](http://www.ajaxcontroltoolkit.com/CascadingDropDown/CascadingDropDown.aspx) I showed then your getter and/or setter would handle the wait there.

If you're using helper methods to cause an action, say logging on, then your wait would be handled there.

Mail me if that didn't help.

Thanks for the kind words!
